name: qdamono
description: A tool for qualitative data analysis.
publish_to: 'none' 
version: 1.0.0-alpha

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  multi_split_view: ^2.0.0
  uuid: ^3.0.6
  file_picker: ^5.2.5
  scrollable_positioned_list: ^0.3.2
  flex_color_picker: ^3.1.0
  socket_io_client: ^2.0.1
  csv: ^5.0.1
  shared_preferences: ^2.0.15
  archive: ^3.3.0
  xml: ^6.1.0
  http: ^0.13.5
  flutter_riverpod: ^2.3.4
  riverpod_annotation: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    # Icon provided by Stockio.com (https://www.stockio.com/free-icon/grapes-2)
    - assets/icon/icon.png
